### PR TITLE
fix: Quaternion fromArray and toArray signatures

### LINKED ISSUE #1229: Quaternion.fromArray() doesn't allow arbitrary length arrays
From thread https://github.com/three-types/three-ts-types/pull/426#issuecomment-2357018628

Similarly, toArray has a quirk where it suggests a QuaternionTuple return type which isn't always the case.

Just filing an issue for this so I can follow the CONTRIBUTING branch naming guidelines.

I'll submit a PR to align the fromArray and toArray types for Quaternion with how it's written for Vector3.

### PR DESCRIPTION
**Pull request by mattrossman**
Updates the Quaternion overloads for fromArray and toArray to align with Vector3's implementation as discussed here:
https://github.com/three-types/three-ts-types/pull/426#issuecomment-2357216535

Resolves #1229 

Per the [CONTRIBUTING guidelines](https://github.com/three-types/three-ts-types/blob/master/CONTRIBUTING.md#testing) I tried to run tests after my changes (and add tests of my own) but running `pnpm run test` for me fails with:

```
> @ test /Users/matt/Code/three-ts-types
> node --require source-map-support/register node_modules/@definitelytyped/dtslint/ types/three

dtslint@0.2.23
Error: ENOENT: no such file or directory, open '/Users/matt/Code/three-ts-types/notNeededPackages.json'
```

I don't see a `notNeededPackage.json` file in the repository despite its mention in the README, so maybe these instructions or testbed are out of date. If a maintainer could provide more instruction on how to run tests I'm happy to add some test cases.

### CODE REVIEW

File: types/three/src/math/Quaternion.d.ts [hunk 1]
```diff
@@ -138,14 +138,15 @@ export class Quaternion {
      * @return The created or provided array.
      */
     toArray(array?: number[], offset?: number): QuaternionTuple;
+    toArray(array?: QuaternionTuple, offset?: 0): QuaternionTuple;
```
Comment (Methuselah96) [inline types/three/src/math/Quaternion.d.ts]: Should the return type of line 140 be updated to `number[]`?

Comment (mattrossman) [reply types/three/src/math/Quaternion.d.ts]: Yes, fixed!

**Review by Methuselah96 — APPROVED** [review]
Thanks! Not sure why local testing is not working, I'll try to look into that.
